### PR TITLE
Fix React 17 support

### PR DESCRIPTION
**Pull request by AmsterGet**
Avoid errors during npm install with React 17.x.

### CODE REVIEW

**Comment by Ngineer101** [comment]
Hi @AmsterGet, unfortunately, I have other projects requiring my attention at the moment. I won't have time in the near future to maintain this project. But, I am happy to accept PRs at any time :)

**Comment by AmsterGet** [comment]
Got it, thanks for merging!
Is it supposed to be published on NPM?

**Comment by Ngineer101** [comment]
Yes, I will publish it soon.

**Comment by Ngineer101** [comment]
Published - https://www.npmjs.com/package/react-image-video-lightbox?activeTab=versions :)

**Pull request merged**
